apiVersion: v1
kind: Namespace
metadata:
  name: corefid
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auditoria-config
  namespace: corefid
data:
  ASPNETCORE_ENVIRONMENT: Production
  Database__MigrarAlIniciar: "false"
  Jwt__Issuer: https://sts.windows.net/eval-tenant/
  Jwt__Audience: api://corefid-audit
  Jwt__Authority: https://login.microsoftonline.com/eval-tenant/v2.0
  Jwt__RequireHttpsMetadata: "true"
  RabbitMq__Habilitado: "true"
  RabbitMq__Host: rabbitmq.mensajeria.svc.cluster.local
  RabbitMq__Exchange: corefid.auditoria
  Outbox__IntervaloSegundos: "5"
  Outbox__TamanoLote: "100"
  Consulta__MaximoResultados: "0"
---
apiVersion: v1
kind: Secret
metadata:
  name: auditoria-secrets
  namespace: corefid
type: Opaque
stringData:
  ConnectionStrings__Auditoria: "REEMPLAZAR_DESDE_VAULT_O_SEALED_SECRETS"
  RabbitMq__Usuario: "REEMPLAZAR"
  RabbitMq__Password: "REEMPLAZAR"
